import type { NextPage } from 'next'
import Head from 'next/head';
// import Image from 'next/image';
import { ThemeProvider } from 'styled-components';

import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Aniversariantes Feitosa
        </h1>

        <p className={styles.description}>
          Visualize as datas de aniversário da família.
        </p>
        <a href="https://nextjs.org/docs" className={styles.card}>
          <iframe src="https://calendar.google.com/calendar/embed?height=800&wkst=1&bgcolor=%23ffffff&ctz=America%2FSao_Paulo&showTitle=0&showNav=0&showPrint=0&showTabs=1&showCalendars=0&showTz=0&mode=AGENDA&src=cWFtdHJjZm5ncDdoMTllNHJtcWFjMWUzY3NAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&color=%238E24AA" style={{border: 0}} scrolling="no"></iframe>
        </a>

        <div className={styles.grid}>

          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by {' '}
          <span className={styles.logo}>
            @oviniciusfeitosa
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
